version: '2'
services:
  web:
    build: .
    command: rails server -p 8080 -b '0.0.0.0'
    volumes:
      - .:/docker
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: postgres:9.4.1
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker